### ISSUE TITLE
Failed to find discreteseekbar

### ISSUE THREAD

**Issue by frostymarvelous** [HeinrichReimer/material-singleinputform#10]
The library seems to require another module discreteseekbar which is not included. 

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find Android-SingleInputForm:discreteseekbar:unspecified.
     Searched in the following locations:
         https://jcenter.bintray.com/Android-SingleInputForm/discreteseekbar/unspecified/discreteseekbar-unspecified.pom
         https://jcenter.bintray.com/Android-SingleInputForm/discreteseekbar/unspecified/discreteseekbar-unspecified.jar
         file:/C:/Users/IBM_ADMIN/AppData/Local/Android/sdk/extras/android/m2repository/Android-SingleInputForm/discreteseekbar/unspecified/discreteseekbar-unspecified.pom
         file:/C:/Users/IBM_ADMIN/AppData/Local/Android/sdk/extras/android/m2repository/Android-SingleInputForm/discreteseekbar/unspecified/discreteseekbar-unspecified.jar
         file:/C:/Users/IBM_ADMIN/AppData/Local/Android/sdk/extras/google/m2repository/Android-SingleInputForm/discreteseekbar/unspecified/discreteseekbar-unspecified.pom
         file:/C:/Users/IBM_ADMIN/AppData/Local/Android/sdk/extras/google/m2repository/Android-SingleInputForm/discreteseekbar/unspecified/discreteseekbar-unspecified.jar
     Required by:
         uma:app:unspecified > com.heinrichreimersoftware.singleinputform:library:2.0

**Comment by HeinrichReimer** [comment]
Duplicate of #9
