### ISSUE TITLE
Activity finished after last step

### ISSUE THREAD

**Issue by frostymarvelous** [HeinrichReimer/material-singleinputform#11]
I noticed that the activity closed automatically after the last step. 
Checking the code, I noticed you call finish after onFormFinished. Is there a reason for this? 
Personally I wanted d to post some data to the server. Is there some special reason for this? If not, I can send a pull request.

**Comment by HeinrichReimer** [comment]
Feel free to send a pull request

**Comment by frostymarvelous** [comment]
Fixed by https://github.com/HeinrichReimer/material-singleinputform/pull/13

**Comment by HeinrichReimer** [comment]
I'll remove the call to `finish()` for the next update.
