### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by JonnyCiel** [HeinrichReimer/material-singleinputform#17]
Hello.

I would like to know how can i place a Toolbar in the view, since i can not override onCreate or onCreateSteps will not be shown.

And how can i center the steps, since they are always on the top on the screen.

Thank you.

**Comment by HeinrichReimer** [comment]
You can do that by having your theme extend one of AppCompat's themes with an action bar and then setting it up with `onCreateOptionsMenu()` and `onOptionsItemSelected()`.

**Comment by HeinrichReimer** [comment]
Ah and you can change the intro gravity using 
```java
SingleInputActivity#setInputGravity(int gravity)
```
