### ISSUE TITLE
incompatible with AppCompat v21

### ISSUE THREAD

**Issue by semsamot** [HeinrichReimer/material-singleinputform#4]
Hi,

It's incompatible with AppCompat v21 because of 'better-pickers' dependency.
See here:
https://github.com/derekbrameyer/android-betterpickers/issues/120

Also here for the solution:
https://github.com/matthew-woolley/android-betterpickers

You may reference it locally since that the original developer was not worried about that!

**Comment by frostymarvelous** [comment]
Any progress?

**Comment by HeinrichReimer** [comment]
I am currently working on a more Material designed Android-SingleInputForm

**Comment by frostymarvelous** [comment]
Thanks. MaterialEditText is a good library to use.

**Comment by HeinrichReimer** [comment]
Fixed it for version 2.0 (5fc4ec531fcdcdd4c54e9b83bc875205b1403c9c)
This release also brings a lot of material goodness.
