### ISSUE TITLE
More step types (keep this open)

### ISSUE THREAD

**Issue by heinrichreimer** [heinrichreimer/material-singleinputform#6]
Please leave your comments, which `Step` types are you missing most.

Planned:
- `CheckBoxStep`
- `SeekBarStep`

**Comment by HeinrichReimer** [comment]
I added material themed `CheckBoxStep` and `SeekBarStep` in version 2.0 (5fc4ec5).
Looking for more ideas...

**Comment by tuhin10** [comment]
Please add file picker(Image) step and location picker step.

**Comment by HeinrichReimer** [comment]
File picker and location pickers are both step types that would need large external libraries like Google Play Services. Such large changes won't be included in the library. However, you can build your own `FilePickerStep` and `LocationPickerStep` and use it with this library if you want.
